<script type="text/javascript" src="{{asset('vote/js/_jq.js')}}"></script>
<script type="text/javascript" src="{{asset('vote/js/_jquery.placeholder.js')}}"></script>
<script src="{{asset('vote/js/activeaxon_menu.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/animationEnigne.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/ie-fixes.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jq.appear.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.base64.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.carouFredSel-6.2.1-packed.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.cycle.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.cycle2.carousel.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.easing.1.3.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.easytabs.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.infinitescroll.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.isotope.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.prettyPhoto.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jQuery.scrollPoint.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.themepunch.plugins.min.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.themepunch.revolution.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.tipsy.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jquery.validate.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/jQuery.XDomainRequest.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/kanzi.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/retina.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/timeago.js')}}" type="text/javascript"></script>
<script src="{{asset('vote/js/tweetable.jquery.js')}}" type="text/javascript"></script>
